/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReportExampleRouteImport } from './routes/report.example'
import { Route as ApiSendReportEmailRouteImport } from './routes/api/send-report-email'
import { Route as ApiRequestFullReportRouteImport } from './routes/api/request-full-report'
import { Route as ApiMarketSignalsRouteImport } from './routes/api/market-signals'
import { Route as ApiGenerateReportPdfRouteImport } from './routes/api/generate-report-pdf'
import { Route as ApiAnalyzePublicV1RouteImport } from './routes/api/analyze-public-v1'
import { Route as AnalyzeUsernameRouteImport } from './routes/analyze.$username'
import { Route as AdminVisaoGeralRouteImport } from './routes/admin.visao-geral'
import { Route as AdminSistemaRouteImport } from './routes/admin.sistema'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminReceitaRouteImport } from './routes/admin.receita'
import { Route as AdminPerfisRouteImport } from './routes/admin.perfis'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as ApiAdminWhoamiRouteImport } from './routes/api/admin/whoami'
import { Route as ApiAdminResendEmailRouteImport } from './routes/api/admin/resend-email'
import { Route as ApiAdminReportsRouteImport } from './routes/api/admin/reports'
import { Route as ApiAdminReportRequestsRouteImport } from './routes/api/admin/report-requests'
import { Route as ApiAdminRegeneratePdfRouteImport } from './routes/api/admin/regenerate-pdf'
import { Route as ApiAdminDiagnosticsRouteImport } from './routes/api/admin/diagnostics'
import { Route as ApiAdminDataforseoDiagnosticsRouteImport } from './routes/api/admin/dataforseo-diagnostics'
import { Route as AdminSistemaCockpitLegadoRouteImport } from './routes/admin.sistema.cockpit-legado'
import { Route as AdminReportPreviewUsernameRouteImport } from './routes/admin.report-preview.$username'
import { Route as ApiPublicAnalysisSnapshotUsernameRouteImport } from './routes/api/public/analysis-snapshot.$username'
import { Route as ApiAdminSnapshotUsernameRouteImport } from './routes/api/admin/snapshot.$username'
import { Route as ApiAdminSnapshotByIdSnapshotIdRouteImport } from './routes/api/admin/snapshot-by-id.$snapshotId'
import { Route as ApiAdminReportsCleanupExpiredRouteImport } from './routes/api/admin/reports.cleanup-expired'
import { Route as ApiAdminReportRequestsIdRouteImport } from './routes/api/admin/report-requests.$id'
import { Route as AdminReportPreviewSnapshotSnapshotIdRouteImport } from './routes/admin.report-preview.snapshot.$snapshotId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReportExampleRoute = ReportExampleRouteImport.update({
  id: '/report/example',
  path: '/report/example',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendReportEmailRoute = ApiSendReportEmailRouteImport.update({
  id: '/api/send-report-email',
  path: '/api/send-report-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestFullReportRoute = ApiRequestFullReportRouteImport.update({
  id: '/api/request-full-report',
  path: '/api/request-full-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketSignalsRoute = ApiMarketSignalsRouteImport.update({
  id: '/api/market-signals',
  path: '/api/market-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReportPdfRoute = ApiGenerateReportPdfRouteImport.update({
  id: '/api/generate-report-pdf',
  path: '/api/generate-report-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzePublicV1Route = ApiAnalyzePublicV1RouteImport.update({
  id: '/api/analyze-public-v1',
  path: '/api/analyze-public-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeUsernameRoute = AnalyzeUsernameRouteImport.update({
  id: '/analyze/$username',
  path: '/analyze/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisaoGeralRoute = AdminVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSistemaRoute = AdminSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitaRoute = AdminReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfisRoute = AdminPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminWhoamiRoute = ApiAdminWhoamiRouteImport.update({
  id: '/api/admin/whoami',
  path: '/api/admin/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResendEmailRoute = ApiAdminResendEmailRouteImport.update({
  id: '/api/admin/resend-email',
  path: '/api/admin/resend-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportsRoute = ApiAdminReportsRouteImport.update({
  id: '/api/admin/reports',
  path: '/api/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReportRequestsRoute = ApiAdminReportRequestsRouteImport.update({
  id: '/api/admin/report-requests',
  path: '/api/admin/report-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRegeneratePdfRoute = ApiAdminRegeneratePdfRouteImport.update({
  id: '/api/admin/regenerate-pdf',
  path: '/api/admin/regenerate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDiagnosticsRoute = ApiAdminDiagnosticsRouteImport.update({
  id: '/api/admin/diagnostics',
  path: '/api/admin/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDataforseoDiagnosticsRoute =
  ApiAdminDataforseoDiagnosticsRouteImport.update({
    id: '/api/admin/dataforseo-diagnostics',
    path: '/api/admin/dataforseo-diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSistemaCockpitLegadoRoute =
  AdminSistemaCockpitLegadoRouteImport.update({
    id: '/cockpit-legado',
    path: '/cockpit-legado',
    getParentRoute: () => AdminSistemaRoute,
  } as any)
const AdminReportPreviewUsernameRoute =
  AdminReportPreviewUsernameRouteImport.update({
    id: '/report-preview/$username',
    path: '/report-preview/$username',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiPublicAnalysisSnapshotUsernameRoute =
  ApiPublicAnalysisSnapshotUsernameRouteImport.update({
    id: '/api/public/analysis-snapshot/$username',
    path: '/api/public/analysis-snapshot/$username',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSnapshotUsernameRoute =
  ApiAdminSnapshotUsernameRouteImport.update({
    id: '/api/admin/snapshot/$username',
    path: '/api/admin/snapshot/$username',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSnapshotByIdSnapshotIdRoute =
  ApiAdminSnapshotByIdSnapshotIdRouteImport.update({
    id: '/api/admin/snapshot-by-id/$snapshotId',
    path: '/api/admin/snapshot-by-id/$snapshotId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminReportsCleanupExpiredRoute =
  ApiAdminReportsCleanupExpiredRouteImport.update({
    id: '/cleanup-expired',
    path: '/cleanup-expired',
    getParentRoute: () => ApiAdminReportsRoute,
  } as any)
const ApiAdminReportRequestsIdRoute =
  ApiAdminReportRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminReportRequestsRoute,
  } as any)
const AdminReportPreviewSnapshotSnapshotIdRoute =
  AdminReportPreviewSnapshotSnapshotIdRouteImport.update({
    id: '/report-preview/snapshot/$snapshotId',
    path: '/report-preview/snapshot/$snapshotId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sistema': typeof AdminSistemaRouteWithChildren
  '/admin/visao-geral': typeof AdminVisaoGeralRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/analyze-public-v1': typeof ApiAnalyzePublicV1Route
  '/api/generate-report-pdf': typeof ApiGenerateReportPdfRoute
  '/api/market-signals': typeof ApiMarketSignalsRoute
  '/api/request-full-report': typeof ApiRequestFullReportRoute
  '/api/send-report-email': typeof ApiSendReportEmailRoute
  '/report/example': typeof ReportExampleRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/report-preview/$username': typeof AdminReportPreviewUsernameRoute
  '/admin/sistema/cockpit-legado': typeof AdminSistemaCockpitLegadoRoute
  '/api/admin/dataforseo-diagnostics': typeof ApiAdminDataforseoDiagnosticsRoute
  '/api/admin/diagnostics': typeof ApiAdminDiagnosticsRoute
  '/api/admin/regenerate-pdf': typeof ApiAdminRegeneratePdfRoute
  '/api/admin/report-requests': typeof ApiAdminReportRequestsRouteWithChildren
  '/api/admin/reports': typeof ApiAdminReportsRouteWithChildren
  '/api/admin/resend-email': typeof ApiAdminResendEmailRoute
  '/api/admin/whoami': typeof ApiAdminWhoamiRoute
  '/admin/report-preview/snapshot/$snapshotId': typeof AdminReportPreviewSnapshotSnapshotIdRoute
  '/api/admin/report-requests/$id': typeof ApiAdminReportRequestsIdRoute
  '/api/admin/reports/cleanup-expired': typeof ApiAdminReportsCleanupExpiredRoute
  '/api/admin/snapshot-by-id/$snapshotId': typeof ApiAdminSnapshotByIdSnapshotIdRoute
  '/api/admin/snapshot/$username': typeof ApiAdminSnapshotUsernameRoute
  '/api/public/analysis-snapshot/$username': typeof ApiPublicAnalysisSnapshotUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sistema': typeof AdminSistemaRouteWithChildren
  '/admin/visao-geral': typeof AdminVisaoGeralRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/analyze-public-v1': typeof ApiAnalyzePublicV1Route
  '/api/generate-report-pdf': typeof ApiGenerateReportPdfRoute
  '/api/market-signals': typeof ApiMarketSignalsRoute
  '/api/request-full-report': typeof ApiRequestFullReportRoute
  '/api/send-report-email': typeof ApiSendReportEmailRoute
  '/report/example': typeof ReportExampleRoute
  '/admin': typeof AdminIndexRoute
  '/admin/report-preview/$username': typeof AdminReportPreviewUsernameRoute
  '/admin/sistema/cockpit-legado': typeof AdminSistemaCockpitLegadoRoute
  '/api/admin/dataforseo-diagnostics': typeof ApiAdminDataforseoDiagnosticsRoute
  '/api/admin/diagnostics': typeof ApiAdminDiagnosticsRoute
  '/api/admin/regenerate-pdf': typeof ApiAdminRegeneratePdfRoute
  '/api/admin/report-requests': typeof ApiAdminReportRequestsRouteWithChildren
  '/api/admin/reports': typeof ApiAdminReportsRouteWithChildren
  '/api/admin/resend-email': typeof ApiAdminResendEmailRoute
  '/api/admin/whoami': typeof ApiAdminWhoamiRoute
  '/admin/report-preview/snapshot/$snapshotId': typeof AdminReportPreviewSnapshotSnapshotIdRoute
  '/api/admin/report-requests/$id': typeof ApiAdminReportRequestsIdRoute
  '/api/admin/reports/cleanup-expired': typeof ApiAdminReportsCleanupExpiredRoute
  '/api/admin/snapshot-by-id/$snapshotId': typeof ApiAdminSnapshotByIdSnapshotIdRoute
  '/api/admin/snapshot/$username': typeof ApiAdminSnapshotUsernameRoute
  '/api/public/analysis-snapshot/$username': typeof ApiPublicAnalysisSnapshotUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/sistema': typeof AdminSistemaRouteWithChildren
  '/admin/visao-geral': typeof AdminVisaoGeralRoute
  '/analyze/$username': typeof AnalyzeUsernameRoute
  '/api/analyze-public-v1': typeof ApiAnalyzePublicV1Route
  '/api/generate-report-pdf': typeof ApiGenerateReportPdfRoute
  '/api/market-signals': typeof ApiMarketSignalsRoute
  '/api/request-full-report': typeof ApiRequestFullReportRoute
  '/api/send-report-email': typeof ApiSendReportEmailRoute
  '/report/example': typeof ReportExampleRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/report-preview/$username': typeof AdminReportPreviewUsernameRoute
  '/admin/sistema/cockpit-legado': typeof AdminSistemaCockpitLegadoRoute
  '/api/admin/dataforseo-diagnostics': typeof ApiAdminDataforseoDiagnosticsRoute
  '/api/admin/diagnostics': typeof ApiAdminDiagnosticsRoute
  '/api/admin/regenerate-pdf': typeof ApiAdminRegeneratePdfRoute
  '/api/admin/report-requests': typeof ApiAdminReportRequestsRouteWithChildren
  '/api/admin/reports': typeof ApiAdminReportsRouteWithChildren
  '/api/admin/resend-email': typeof ApiAdminResendEmailRoute
  '/api/admin/whoami': typeof ApiAdminWhoamiRoute
  '/admin/report-preview/snapshot/$snapshotId': typeof AdminReportPreviewSnapshotSnapshotIdRoute
  '/api/admin/report-requests/$id': typeof ApiAdminReportRequestsIdRoute
  '/api/admin/reports/cleanup-expired': typeof ApiAdminReportsCleanupExpiredRoute
  '/api/admin/snapshot-by-id/$snapshotId': typeof ApiAdminSnapshotByIdSnapshotIdRoute
  '/api/admin/snapshot/$username': typeof ApiAdminSnapshotUsernameRoute
  '/api/public/analysis-snapshot/$username': typeof ApiPublicAnalysisSnapshotUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/design-system'
    | '/privacidade'
    | '/termos'
    | '/admin/clientes'
    | '/admin/perfis'
    | '/admin/receita'
    | '/admin/relatorios'
    | '/admin/sistema'
    | '/admin/visao-geral'
    | '/analyze/$username'
    | '/api/analyze-public-v1'
    | '/api/generate-report-pdf'
    | '/api/market-signals'
    | '/api/request-full-report'
    | '/api/send-report-email'
    | '/report/example'
    | '/admin/'
    | '/admin/report-preview/$username'
    | '/admin/sistema/cockpit-legado'
    | '/api/admin/dataforseo-diagnostics'
    | '/api/admin/diagnostics'
    | '/api/admin/regenerate-pdf'
    | '/api/admin/report-requests'
    | '/api/admin/reports'
    | '/api/admin/resend-email'
    | '/api/admin/whoami'
    | '/admin/report-preview/snapshot/$snapshotId'
    | '/api/admin/report-requests/$id'
    | '/api/admin/reports/cleanup-expired'
    | '/api/admin/snapshot-by-id/$snapshotId'
    | '/api/admin/snapshot/$username'
    | '/api/public/analysis-snapshot/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/privacidade'
    | '/termos'
    | '/admin/clientes'
    | '/admin/perfis'
    | '/admin/receita'
    | '/admin/relatorios'
    | '/admin/sistema'
    | '/admin/visao-geral'
    | '/analyze/$username'
    | '/api/analyze-public-v1'
    | '/api/generate-report-pdf'
    | '/api/market-signals'
    | '/api/request-full-report'
    | '/api/send-report-email'
    | '/report/example'
    | '/admin'
    | '/admin/report-preview/$username'
    | '/admin/sistema/cockpit-legado'
    | '/api/admin/dataforseo-diagnostics'
    | '/api/admin/diagnostics'
    | '/api/admin/regenerate-pdf'
    | '/api/admin/report-requests'
    | '/api/admin/reports'
    | '/api/admin/resend-email'
    | '/api/admin/whoami'
    | '/admin/report-preview/snapshot/$snapshotId'
    | '/api/admin/report-requests/$id'
    | '/api/admin/reports/cleanup-expired'
    | '/api/admin/snapshot-by-id/$snapshotId'
    | '/api/admin/snapshot/$username'
    | '/api/public/analysis-snapshot/$username'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/design-system'
    | '/privacidade'
    | '/termos'
    | '/admin/clientes'
    | '/admin/perfis'
    | '/admin/receita'
    | '/admin/relatorios'
    | '/admin/sistema'
    | '/admin/visao-geral'
    | '/analyze/$username'
    | '/api/analyze-public-v1'
    | '/api/generate-report-pdf'
    | '/api/market-signals'
    | '/api/request-full-report'
    | '/api/send-report-email'
    | '/report/example'
    | '/admin/'
    | '/admin/report-preview/$username'
    | '/admin/sistema/cockpit-legado'
    | '/api/admin/dataforseo-diagnostics'
    | '/api/admin/diagnostics'
    | '/api/admin/regenerate-pdf'
    | '/api/admin/report-requests'
    | '/api/admin/reports'
    | '/api/admin/resend-email'
    | '/api/admin/whoami'
    | '/admin/report-preview/snapshot/$snapshotId'
    | '/api/admin/report-requests/$id'
    | '/api/admin/reports/cleanup-expired'
    | '/api/admin/snapshot-by-id/$snapshotId'
    | '/api/admin/snapshot/$username'
    | '/api/public/analysis-snapshot/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AnalyzeUsernameRoute: typeof AnalyzeUsernameRoute
  ApiAnalyzePublicV1Route: typeof ApiAnalyzePublicV1Route
  ApiGenerateReportPdfRoute: typeof ApiGenerateReportPdfRoute
  ApiMarketSignalsRoute: typeof ApiMarketSignalsRoute
  ApiRequestFullReportRoute: typeof ApiRequestFullReportRoute
  ApiSendReportEmailRoute: typeof ApiSendReportEmailRoute
  ReportExampleRoute: typeof ReportExampleRoute
  ApiAdminDataforseoDiagnosticsRoute: typeof ApiAdminDataforseoDiagnosticsRoute
  ApiAdminDiagnosticsRoute: typeof ApiAdminDiagnosticsRoute
  ApiAdminRegeneratePdfRoute: typeof ApiAdminRegeneratePdfRoute
  ApiAdminReportRequestsRoute: typeof ApiAdminReportRequestsRouteWithChildren
  ApiAdminReportsRoute: typeof ApiAdminReportsRouteWithChildren
  ApiAdminResendEmailRoute: typeof ApiAdminResendEmailRoute
  ApiAdminWhoamiRoute: typeof ApiAdminWhoamiRoute
  ApiAdminSnapshotByIdSnapshotIdRoute: typeof ApiAdminSnapshotByIdSnapshotIdRoute
  ApiAdminSnapshotUsernameRoute: typeof ApiAdminSnapshotUsernameRoute
  ApiPublicAnalysisSnapshotUsernameRoute: typeof ApiPublicAnalysisSnapshotUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/report/example': {
      id: '/report/example'
      path: '/report/example'
      fullPath: '/report/example'
      preLoaderRoute: typeof ReportExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-report-email': {
      id: '/api/send-report-email'
      path: '/api/send-report-email'
      fullPath: '/api/send-report-email'
      preLoaderRoute: typeof ApiSendReportEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-full-report': {
      id: '/api/request-full-report'
      path: '/api/request-full-report'
      fullPath: '/api/request-full-report'
      preLoaderRoute: typeof ApiRequestFullReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-signals': {
      id: '/api/market-signals'
      path: '/api/market-signals'
      fullPath: '/api/market-signals'
      preLoaderRoute: typeof ApiMarketSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-report-pdf': {
      id: '/api/generate-report-pdf'
      path: '/api/generate-report-pdf'
      fullPath: '/api/generate-report-pdf'
      preLoaderRoute: typeof ApiGenerateReportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-public-v1': {
      id: '/api/analyze-public-v1'
      path: '/api/analyze-public-v1'
      fullPath: '/api/analyze-public-v1'
      preLoaderRoute: typeof ApiAnalyzePublicV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$username': {
      id: '/analyze/$username'
      path: '/analyze/$username'
      fullPath: '/analyze/$username'
      preLoaderRoute: typeof AnalyzeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visao-geral': {
      id: '/admin/visao-geral'
      path: '/visao-geral'
      fullPath: '/admin/visao-geral'
      preLoaderRoute: typeof AdminVisaoGeralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sistema': {
      id: '/admin/sistema'
      path: '/sistema'
      fullPath: '/admin/sistema'
      preLoaderRoute: typeof AdminSistemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receita': {
      id: '/admin/receita'
      path: '/receita'
      fullPath: '/admin/receita'
      preLoaderRoute: typeof AdminReceitaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfis': {
      id: '/admin/perfis'
      path: '/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AdminPerfisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/whoami': {
      id: '/api/admin/whoami'
      path: '/api/admin/whoami'
      fullPath: '/api/admin/whoami'
      preLoaderRoute: typeof ApiAdminWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resend-email': {
      id: '/api/admin/resend-email'
      path: '/api/admin/resend-email'
      fullPath: '/api/admin/resend-email'
      preLoaderRoute: typeof ApiAdminResendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports': {
      id: '/api/admin/reports'
      path: '/api/admin/reports'
      fullPath: '/api/admin/reports'
      preLoaderRoute: typeof ApiAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/report-requests': {
      id: '/api/admin/report-requests'
      path: '/api/admin/report-requests'
      fullPath: '/api/admin/report-requests'
      preLoaderRoute: typeof ApiAdminReportRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/regenerate-pdf': {
      id: '/api/admin/regenerate-pdf'
      path: '/api/admin/regenerate-pdf'
      fullPath: '/api/admin/regenerate-pdf'
      preLoaderRoute: typeof ApiAdminRegeneratePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/diagnostics': {
      id: '/api/admin/diagnostics'
      path: '/api/admin/diagnostics'
      fullPath: '/api/admin/diagnostics'
      preLoaderRoute: typeof ApiAdminDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dataforseo-diagnostics': {
      id: '/api/admin/dataforseo-diagnostics'
      path: '/api/admin/dataforseo-diagnostics'
      fullPath: '/api/admin/dataforseo-diagnostics'
      preLoaderRoute: typeof ApiAdminDataforseoDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sistema/cockpit-legado': {
      id: '/admin/sistema/cockpit-legado'
      path: '/cockpit-legado'
      fullPath: '/admin/sistema/cockpit-legado'
      preLoaderRoute: typeof AdminSistemaCockpitLegadoRouteImport
      parentRoute: typeof AdminSistemaRoute
    }
    '/admin/report-preview/$username': {
      id: '/admin/report-preview/$username'
      path: '/report-preview/$username'
      fullPath: '/admin/report-preview/$username'
      preLoaderRoute: typeof AdminReportPreviewUsernameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/analysis-snapshot/$username': {
      id: '/api/public/analysis-snapshot/$username'
      path: '/api/public/analysis-snapshot/$username'
      fullPath: '/api/public/analysis-snapshot/$username'
      preLoaderRoute: typeof ApiPublicAnalysisSnapshotUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/snapshot/$username': {
      id: '/api/admin/snapshot/$username'
      path: '/api/admin/snapshot/$username'
      fullPath: '/api/admin/snapshot/$username'
      preLoaderRoute: typeof ApiAdminSnapshotUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/snapshot-by-id/$snapshotId': {
      id: '/api/admin/snapshot-by-id/$snapshotId'
      path: '/api/admin/snapshot-by-id/$snapshotId'
      fullPath: '/api/admin/snapshot-by-id/$snapshotId'
      preLoaderRoute: typeof ApiAdminSnapshotByIdSnapshotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reports/cleanup-expired': {
      id: '/api/admin/reports/cleanup-expired'
      path: '/cleanup-expired'
      fullPath: '/api/admin/reports/cleanup-expired'
      preLoaderRoute: typeof ApiAdminReportsCleanupExpiredRouteImport
      parentRoute: typeof ApiAdminReportsRoute
    }
    '/api/admin/report-requests/$id': {
      id: '/api/admin/report-requests/$id'
      path: '/$id'
      fullPath: '/api/admin/report-requests/$id'
      preLoaderRoute: typeof ApiAdminReportRequestsIdRouteImport
      parentRoute: typeof ApiAdminReportRequestsRoute
    }
    '/admin/report-preview/snapshot/$snapshotId': {
      id: '/admin/report-preview/snapshot/$snapshotId'
      path: '/report-preview/snapshot/$snapshotId'
      fullPath: '/admin/report-preview/snapshot/$snapshotId'
      preLoaderRoute: typeof AdminReportPreviewSnapshotSnapshotIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminSistemaRouteChildren {
  AdminSistemaCockpitLegadoRoute: typeof AdminSistemaCockpitLegadoRoute
}

const AdminSistemaRouteChildren: AdminSistemaRouteChildren = {
  AdminSistemaCockpitLegadoRoute: AdminSistemaCockpitLegadoRoute,
}

const AdminSistemaRouteWithChildren = AdminSistemaRoute._addFileChildren(
  AdminSistemaRouteChildren,
)

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminPerfisRoute: typeof AdminPerfisRoute
  AdminReceitaRoute: typeof AdminReceitaRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSistemaRoute: typeof AdminSistemaRouteWithChildren
  AdminVisaoGeralRoute: typeof AdminVisaoGeralRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportPreviewUsernameRoute: typeof AdminReportPreviewUsernameRoute
  AdminReportPreviewSnapshotSnapshotIdRoute: typeof AdminReportPreviewSnapshotSnapshotIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminPerfisRoute: AdminPerfisRoute,
  AdminReceitaRoute: AdminReceitaRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSistemaRoute: AdminSistemaRouteWithChildren,
  AdminVisaoGeralRoute: AdminVisaoGeralRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportPreviewUsernameRoute: AdminReportPreviewUsernameRoute,
  AdminReportPreviewSnapshotSnapshotIdRoute:
    AdminReportPreviewSnapshotSnapshotIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminReportRequestsRouteChildren {
  ApiAdminReportRequestsIdRoute: typeof ApiAdminReportRequestsIdRoute
}

const ApiAdminReportRequestsRouteChildren: ApiAdminReportRequestsRouteChildren =
  {
    ApiAdminReportRequestsIdRoute: ApiAdminReportRequestsIdRoute,
  }

const ApiAdminReportRequestsRouteWithChildren =
  ApiAdminReportRequestsRoute._addFileChildren(
    ApiAdminReportRequestsRouteChildren,
  )

interface ApiAdminReportsRouteChildren {
  ApiAdminReportsCleanupExpiredRoute: typeof ApiAdminReportsCleanupExpiredRoute
}

const ApiAdminReportsRouteChildren: ApiAdminReportsRouteChildren = {
  ApiAdminReportsCleanupExpiredRoute: ApiAdminReportsCleanupExpiredRoute,
}

const ApiAdminReportsRouteWithChildren = ApiAdminReportsRoute._addFileChildren(
  ApiAdminReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AnalyzeUsernameRoute: AnalyzeUsernameRoute,
  ApiAnalyzePublicV1Route: ApiAnalyzePublicV1Route,
  ApiGenerateReportPdfRoute: ApiGenerateReportPdfRoute,
  ApiMarketSignalsRoute: ApiMarketSignalsRoute,
  ApiRequestFullReportRoute: ApiRequestFullReportRoute,
  ApiSendReportEmailRoute: ApiSendReportEmailRoute,
  ReportExampleRoute: ReportExampleRoute,
  ApiAdminDataforseoDiagnosticsRoute: ApiAdminDataforseoDiagnosticsRoute,
  ApiAdminDiagnosticsRoute: ApiAdminDiagnosticsRoute,
  ApiAdminRegeneratePdfRoute: ApiAdminRegeneratePdfRoute,
  ApiAdminReportRequestsRoute: ApiAdminReportRequestsRouteWithChildren,
  ApiAdminReportsRoute: ApiAdminReportsRouteWithChildren,
  ApiAdminResendEmailRoute: ApiAdminResendEmailRoute,
  ApiAdminWhoamiRoute: ApiAdminWhoamiRoute,
  ApiAdminSnapshotByIdSnapshotIdRoute: ApiAdminSnapshotByIdSnapshotIdRoute,
  ApiAdminSnapshotUsernameRoute: ApiAdminSnapshotUsernameRoute,
  ApiPublicAnalysisSnapshotUsernameRoute:
    ApiPublicAnalysisSnapshotUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
